import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const base=process.env.SITE_URL || 'https://stevenybuilder.github.io';
const cssVersion=createHash('sha256').update(readFileSync(path.join(root,'assets/site.css'))).digest('hex').slice(0,10);
const jsVersion=createHash('sha256').update(readFileSync(path.join(root,'assets/site.js'))).digest('hex').slice(0,10);
const postTitle='Changing a robot’s mind';
const subtitle='Pick It Up: Does π0.5 Have an Editable Instruction Following Circuit?';
const links=[['question','The question'],['importance','Why it matters'],['rollouts','Finding 1: Image-state control'],['language','Finding 2: Readable instructions'],['background','Background'],['geometry','Representation geometry'],['limitations','Future directions'],['appendix','Supporting figures'],['references','Code & references']];
const toc=links.map(([id,title])=>`<a href="#${id}">${title}</a>`).join('');
const dose=JSON.parse(readFileSync(path.join(root,'assets/data/dose.json'),'utf8'));
const px=i=>52+i*48,py=v=>238-v*175;
const homeChart=`<svg viewBox="0 0 430 310" role="img" aria-label="Position-dose curve: small patches produce little action progress; all 512 positions produce 0.773." xmlns="http://www.w3.org/2000/svg" style="font:14px sans-serif;fill:#59616a"><text x="52" y="20" fill="#278574">● Object-centered</text><text x="235" y="20" fill="#da8740">● Random</text>${[0,.5,1].map(v=>`<line x1="52" y1="${py(v)}" x2="395" y2="${py(v)}" stroke="#e3e6e8"/><text x="42" y="${py(v)+5}" text-anchor="end">${v.toFixed(1)}</text>`).join('')}${['selected','random'].map((k,j)=>`<polyline points="${dose.map((d,i)=>`${px(i)},${py(d[k])}`).join(' ')}" fill="none" stroke="${j?'#da8740':'#278574'}" stroke-width="2.5"/>`).join('')}${dose.map((d,i)=>`<text x="${px(i)}" y="261" text-anchor="middle">${d.positions}</text>`).join('')}<circle cx="388" cy="${py(dose[7].selected)}" r="4" fill="#386bb0"/><text x="381" y="${py(dose[7].selected)-13}" text-anchor="end" fill="#386bb0" font-weight="bold">${dose[7].selected.toFixed(3)}</text><text x="221" y="298" text-anchor="middle">Image positions replaced</text><text x="16" y="150" transform="rotate(-90 16 150)" text-anchor="middle">Action progress R</text></svg>`;
function page(title,description,body,route='',nav=''){
 if(existsSync(path.join(root,'assets/data/video-hd-provenance.json'))){
  body=body.replace(/\/assets\/media\/(repair|conflict|correct|early)\.(mp4|jpg)/g,'/assets/media/$1-hd.$2');
  body=body.replace(/<video\b/g,'<video data-playback-rate="1"');
  body=body.replace('</div></div><blockquote class="code-callout">','</div></div><p class="figure-note">High-resolution reruns of the illustrated case: matching task outcomes, with up to one simulator step of timing variation.</p><blockquote class="code-callout">');
 }
 if(nav==='home')body=body.replace('<button id="home-play" class="scene-pause" type="button">Play</button>','').replace('<video id="home-video"','<video id="home-video" data-ambient').replace(/<div class="home-plot">[\s\S]*?<\/div>/,`<div class="home-plot">${homeChart}</div>`);
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Steven Yang</title><meta name="description" content="${description}"><link rel="canonical" href="${base}/${route}"><meta property="og:type" content="${route==='pick-it-up/'?'article':'website'}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${base}/${route}"><meta property="og:image" content="${base}/assets/media/position-dose.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="alternate" type="application/rss+xml" title="Steven Yang — Research notes" href="/feed.xml"><link rel="stylesheet" href="/assets/site.css"><script defer src="/assets/site.js"></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="brand" href="/"><span class="brand-mark" aria-hidden="true"><img src="/assets/hippocampus.webp" alt=""></span><span>Steven Yang<span class="brand-sub">A collection of experiments and thoughts</span></span></a><nav class="site-nav" aria-label="Main navigation"><a href="/" ${nav==='home'?'aria-current="page"':''}>Home</a><a href="/writing/" ${nav==='writing'?'aria-current="page"':''}>Writing</a><a href="/about/" ${nav==='about'?'aria-current="page"':''}>About</a></nav></header>${body}<footer class="site-footer"><span>© 2026 Steven Yang</span>${nav==="about"?`<span class="social-links"><a href="mailto:stevenybusiness@gmail.com" aria-label="Email Steven Yang"><img src="/assets/icons/email.svg" alt=""></a><a href="https://github.com/stevenybuilder" aria-label="GitHub"><img src="/assets/icons/github.svg" alt=""></a><a href="https://www.instagram.com/stevenbearyang/" aria-label="Instagram"><img src="/assets/icons/instagram.svg" alt=""></a><a href="https://x.com/stevenytechs" aria-label="X"><img src="/assets/icons/x.svg" alt=""></a></span>`:""}</footer></body></html>`;
}
function out(file,body){mkdirSync(path.dirname(path.join(root,file)),{recursive:true});writeFileSync(path.join(root,file),body.replaceAll('href="/assets/site.css"',`href="/assets/site.css?v=${cssVersion}"`).replaceAll('src="/assets/site.js"',`src="/assets/site.js?v=${jsVersion}"`))}
let article=readFileSync(path.join(root,'content/pick-it-up.html'),'utf8');
article=article.replace(/^(<figure class="figure opening-film">[\s\S]*?<\/figure>)\s*(<section id="question">[\s\S]*?<\/section>)/,'<div class="article-intro">$1$2</div>');
// Keep captions, without report-style numbering that interrupts the blog.
article=article.replace(/<b>Figure \d+\.<\/b>\s*/g,'').replace(/<span class="figure-index">\d+<\/span>/g,'').replace('used in Figure 1','used in the main dose curve');
out('pick-it-up/index.html',page(postTitle,'Broad image-state edits redirect π0.5 robot rollouts. Smaller edits struggle to reproduce the effect.',`<main id="main"><header class="post-header"><h1>${postTitle}</h1><p class="post-subtitle">${subtitle}</p><div class="post-meta"><span>Steven Yang</span><span>·</span><time datetime="2026-09-05">September 5, 2026</time></div><div class="tags"><a href="/writing/?q=interpretability">interpretability</a><a href="/writing/?q=robotics">robotics</a><a href="/writing/?q=VLA">VLA</a></div><div class="post-actions"><a href="https://github.com/stevenybuilder/mechinterp-vla">Code & data ↗</a><a href="#rollouts">Watch the robots ↓</a><a href="#appendix">Supporting figures ↓</a></div></header><details class="mobile-toc"><summary>In this report</summary><nav>${toc}</nav></details><div class="post-layout"><article class="post-body">${article}</article><aside class="side-nav" aria-label="In this report"><p class="eyebrow">In this report</p>${toc}<a class="code-link" href="https://github.com/stevenybuilder/mechinterp-vla">Code & data ↗</a></aside></div></main>`,'pick-it-up/','writing'));
out('index.html',page('Research notes','Steven Yang writes about model biology, mechanistic interpretability, and models that act in the physical world.',`<main id="main" class="home"><div class="home-note"><p>I’m interested in what models learn about the world, and how those representations become actions. This is where I write up my experiments.</p></div><article class="home-post"><header><h1><a href="/pick-it-up/">${postTitle}</a></h1><p class="post-subtitle">${subtitle}</p><div class="post-meta"><time datetime="2026-09-05">September 5, 2026</time><span>·</span><span>Interpretability / Robotics</span></div></header><div class="home-feature-media"><div class="home-video"><video id="home-video" muted playsinline loop preload="metadata" poster="/assets/media/repair.jpg"><source src="/assets/media/repair.mp4" type="video/mp4"></video><button id="home-play" class="scene-pause" type="button">Play</button></div><div class="home-plot"><img src="/assets/media/position-dose.svg" alt="Small position patches barely shift the action; all 512 positions produce a large change."></div></div><p class="home-caption">A late image-state edit redirects the robot to cream cheese. The position-dose curve shows why shrinking that edit proved difficult.</p><p>Identified a causal pathway for instruction control in π0.5, but no evidence for a selectively editable obedience circuit at the token position level.</p><a class="read-more" href="/pick-it-up/">Read the report →</a></article></main>`,'','home'));
out('about/index.html',page('About Me','Steven Yang works on applied interpretability for world models and physical AI.',`<main id="main" class="simple-page"><h1>About Me</h1><p>I’m going after applied interpretability for world models because of the real world consequences of physical AI systems. There is increasing relevance between human neurobiological pathways and model biology in AI.</p><p>I’m currently exploring fine grained steering methods to improve robotics task outcomes off frozen JEPA models.</p><p>In the past, I’ve spent time investigating pattern separation in the hippocampus at UC Irvine’s Center for Neurobiology of Learning and Memory. The focus of my cognitive and computational neuroscience research was on human memory and attention mechanisms. Lots of MRI experiments and analysis!</p><p>During my degree, I also interned at Hoag Hospital and loved seeing the impact I could have on patients in the ICU. Currently, I work as a product manager at Experian, leading our 0 to 1 product development around AI and data science.</p><p>I also compete in martial arts! I’ve trained with UFC athletes and enjoy the constant pursuit of learning and improving.</p><p>If you’re ever in New York drop me a message! Contact links are on the bottom of the page.</p></main>`,'about/','about'));
out('writing/index.html',page('Writing','Research reports and experiments by Steven Yang.',`<main id="main" class="simple-page"><h1>Writing</h1><p>Research reports, experiments, and the things that didn’t work.</p><label for="post-search" class="eyebrow">Find a report</label><input class="search-box" id="post-search" type="search" placeholder="Search by title or topic…"><div class="post-list"><article class="post-item" data-search="changing a robot mind pick it up pi0.5 VLA vision language action interpretability robotics model biology"><div class="eyebrow">September 5, 2026 · Research report</div><h2><a href="/pick-it-up/">${postTitle}</a></h2><p>${subtitle}</p><p>Broad image-state edits redirect robot rollouts. Smaller edits struggle to reproduce the effect.</p><a class="text-link" href="/pick-it-up/">Read →</a></article><p class="empty-state" role="status">No reports match that search.</p></div></main>`,'writing/','writing'));
out('404.html',page('Page not found','This page could not be found.',`<main id="main" class="simple-page"><h1>Page not found</h1><p>That address doesn’t point to a page here.</p><p><a href="/">Back to the homepage →</a></p></main>`));
out('feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Steven Yang — Research notes</title><link>${base}/</link><description>Experiments in model biology and applied interpretability.</description><language>en</language><item><title>${postTitle}</title><link>${base}/pick-it-up/</link><guid>${base}/pick-it-up/</guid><pubDate>Sat, 05 Sep 2026 12:00:00 GMT</pubDate><description>Broad image-state edits redirect π0.5 robot rollouts. Smaller edits struggle to reproduce the effect.</description></item></channel></rss>`);
out('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['','about/','writing/','pick-it-up/'].map(p=>`<url><loc>${base}/${p}</loc><lastmod>2026-09-05</lastmod></url>`).join('')}</urlset>`);
out('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);
out('.nojekyll','');
console.log('Built homepage, About, writing index, research report, RSS, sitemap, and 404.');
